<a href="https://colab.research.google.com/github/joyangelai/Movies_Data/blob/main/movies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing the necessary libraries
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [ ]:
# fetching the dataset to be worked on
movies = pd.read_csv("http://bit.ly/MoviesDataset1")
movies.head(2)

,movie_title,num_critic_for_reviews,duration,DIRECTOR_facebook_likes,actor_3_facebook_likes,ACTOR_1_facebook_likes,gross,num_voted_users,Cast_Total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,ACTOR_2_facebook_likes,imdb_score,title_year.1
0,Avatar?ÿ,723,178.0,10,855,1000,760505847,886204.0,4834.0,NaN,3054,237000000,2009,936.0,7.9,2009.0
1,Pirates of the Caribbean: At World's End?ÿ,302,NaN,563,1000,40000,309404152,471220.0,48350.0,NaN,1238,300000000,2007,5000.0,7.1,NaN

In [ ]:
movies.tail(3)

,movie_title,num_critic_for_reviews,duration,DIRECTOR_facebook_likes,actor_3_facebook_likes,ACTOR_1_facebook_likes,gross,num_voted_users,Cast_Total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,ACTOR_2_facebook_likes,imdb_score,title_year.1
11,Superman Returns?ÿ,434,169.0,NaN,903,18000,200069408,240396.0,NaN,2.0,2367,209000000,2006,10000.0,6.1,NaN
12,Quantum of Solace?ÿ,403,106.0,395,393,451,168368427,330784.0,2023.0,1.0,1243,200000000,2008,412.0,6.7,2008.0
13,Pirates of the Caribbean: Dead Man's Chest?ÿ,313,151.0,563,1000,40000,423032628,522040.0,48486.0,2.0,1832,225000000,2006,5000.0,7.3,2008.0

In [ ]:
# checking the shape
movies.shape

(14, 16)

In [ ]:
# checking the dataset info
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   movie_title                14 non-null     object
 1   num_critic_for_reviews     14 non-null     int64
 2   duration                   11 non-null     float64
 3   DIRECTOR_facebook_likes    12 non-null     object
 4   actor_3_facebook_likes     14 non-null     int64
 5   ACTOR_1_facebook_likes     14 non-null     int64
 6   gross                      14 non-null     int64
 7   num_voted_users            13 non-null     float64
 8   Cast_Total_facebook_likes  12 non-null     float64
 9   facenumber_in_poster       9 non-null      float64
 10  num_user_for_reviews       14 non-null     int64
 11  budget                     14 non-null     int64
 12  title_year                 14 non-null     int64
 13  ACTOR_2_facebook_likes     13 non-null     float64
 14  imdb_score                 14 non-null     float64
 15  title_year.1               7 non-null      float64
dtypes: float64(7), int64(7), object(2)
memory usage: 1.9+ KB

In [ ]:
# check the info again
movies.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Columns: 16 entries, movie_title to title_year.1
dtypes: float64(7), int64(7), object(2)
memory usage: 1.9+ KB

In [ ]:
# check concise summary statistics
movies.describe().T

,count,mean,std,min,25%,50%,75%,max
num_critic_for_reviews,14.0,5.061429e+02,1.690698e+02,302.0,3.792500e+02,448.0,6.350000e+02,813.0
duration,11.0,1.507273e+02,2.167990e+01,106.0,1.410000e+02,151.0,1.625000e+02,183.0
actor_3_facebook_likes,14.0,5.866143e+03,8.289593e+03,161.0,6.112500e+02,1000.0,8.500000e+03,23000.0
ACTOR_1_facebook_likes,14.0,1.820643e+04,1.390521e+04,451.0,3.500000e+03,21000.0,2.600000e+04,40000.0
gross,14.0,3.335836e+08,1.720674e+08,73058679.0,2.002574e+08,319826607.0,4.418561e+08,760505847.0
num_voted_users,13.0,4.621578e+05,2.687059e+05,212204.0,2.948100e+05,383056.0,4.712200e+05,1144337.0
Cast_Total_facebook_likes,12.0,4.477358e+04,3.729081e+04,1873.0,9.983500e+03,47202.5,6.706475e+04,106759.0
facenumber_in_poster,9.0,2.111111e+00,1.269296e+00,1.0,1.000000e+00,2.0,3.000000e+00,4.0
num_user_for_reviews,14.0,1.620071e+03,8.666721e+02,387.0,1.024750e+03,1240.5,2.250750e+03,3054.0
budget,14.0,2.462643e+08,2.426823e+07,200000000.0,2.390000e+08,250000000.0,2.560000e+08,300000000.0
title_year,14.0,2.010500e+03,3.632122e+00,2006.0,2.007250e+03,2009.5,2.014250e+03,2016.0
ACTOR_2_facebook_likes,13.0,8.455846e+03,8.541020e+03,393.0,6.320000e+02,5000.0,1.100000e+04,23000.0
imdb_score,14.0,7.171429e+00,6.730283e-01,6.1,6.725000e+00,7.2,7.500000e+00,8.5
title_year.1,7.0,2.011143e+03,3.976119e+00,2007.0,2.008000e+03,2009.0,2.015000e+03,2016.0

In [ ]:
# describe categorical features
movies.describe(include="O")

                      movie_title DIRECTOR_facebook_likes
count                          14                      12
unique                         13                       9
top     Avengers: Age of Ultron?ÿ                      10
freq                            2                       3

In [ ]:
# creating a copy before beginning data cleaning
movies1 = movies.copy(deep=True)
movies1.head(2)

,movie_title,num_critic_for_reviews,duration,DIRECTOR_facebook_likes,actor_3_facebook_likes,ACTOR_1_facebook_likes,gross,num_voted_users,Cast_Total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,ACTOR_2_facebook_likes,imdb_score,title_year.1
0,Avatar?ÿ,723,178.0,10,855,1000,760505847,886204.0,4834.0,NaN,3054,237000000,2009,936.0,7.9,2009.0
1,Pirates of the Caribbean: At World's End?ÿ,302,NaN,563,1000,40000,309404152,471220.0,48350.0,NaN,1238,300000000,2007,5000.0,7.1,NaN

In [ ]:
# checking unique variable
for i in movies1:
  colval = movies1[i].unique()
  print(f"Column name: {i} \n : {colval}")

Column name: movie_title
 : ['Avatar?ÿ' "Pirates of the Caribbean: At World's End?ÿ" 'Spectre?ÿ'
 'The Dark Knight Rises?ÿ' 'John Carter?ÿ' 'Spider-Man 3?ÿ' 'Tangled?ÿ'
 'Avengers: Age of Ultron?ÿ' 'Harry Potter and the Half-Blood Prince?ÿ'
 'Batman v Superman: Dawn of Justice?ÿ' 'Superman Returns?ÿ'
 'Quantum of Solace?ÿ' "Pirates of the Caribbean: Dead Man's Chest?ÿ"]
Column name: num_critic_for_reviews
 : [723 302 602 813 462 392 324 635 375 673 434 403 313]
Column name: duration
 : [178.  nan 148. 132. 156. 141. 153. 183. 169. 106. 151.]
Column name: DIRECTOR_facebook_likes
 : ['10' '563' '20' '22000' '"475"' '23' '15' '282' nan '395']
Column name: actor_3_facebook_likes
 : [  855  1000   161 23000   530  4000   284 19000 10000  2000   903   393]
Column name: ACTOR_1_facebook_likes
 : [ 1000 40000 11000 27000   640 24000   799 26000 25000 15000 18000   451]
Column name: gross
 : [760505847 309404152 200074175 448130642  73058679 336530303 200807262
 458991599 301956980 330249062 200069408 168368427 423032628]
Column name: num_voted_users
 : [ 886204.  471220.  275868. 1144337.  212204.  383056.  294810.  462669.
  321795.      nan  240396.  330784.  522040.]
Column name: Cast_Total_facebook_likes
 : [  4834.  48350.  11700. 106759.   1873.  46055.     nan  92000.  58753.
  24450.   2023.  48486.]
Column name: facenumber_in_poster
 : [nan  1.  4.  3.  2.]
Column name: num_user_for_reviews
 : [3054 1238  994 2701  738 1902  387 1117  973 3018 2367 1243 1832]
Column name: budget
 : [237000000 300000000 245000000 250000000 263700000 258000000 260000000
 209000000 200000000 225000000]
Column name: title_year
 : [2009 2007 2015 2012 2010 2016 2006 2008]
Column name: ACTOR_2_facebook_likes
 : [  936.  5000.   393. 23000.   632. 11000.   553. 21000.    nan 10000.
   412.]
Column name: imdb_score
 : [7.9 7.1 6.8 8.5 6.6 6.2 7.8 7.5 6.9 6.1 6.7 7.3]
Column name: title_year.1
 : [2009.   nan 2015. 2007. 2016. 2008.]

In [ ]:
# checking columns again
movies1.columns

Index(['movie_title', 'num_critic_for_reviews', 'duration',
       'DIRECTOR_facebook_likes', 'actor_3_facebook_likes',
       'ACTOR_1_facebook_likes', 'gross', 'num_voted_users',
       'Cast_Total_facebook_likes', 'facenumber_in_poster',
       'num_user_for_reviews', 'budget', 'title_year',
       'ACTOR_2_facebook_likes', 'imdb_score', 'title_year.1'],
      dtype='object')

In [ ]:
# convert the columns into lowercase
movies1.columns = movies1.columns.str.lower()
# confirming the changes
movies1.columns

Index(['movie_title', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes',
       'actor_1_facebook_likes', 'gross', 'num_voted_users',
       'cast_total_facebook_likes', 'facenumber_in_poster',
       'num_user_for_reviews', 'budget', 'title_year',
       'actor_2_facebook_likes', 'imdb_score', 'title_year.1'],
      dtype='object')

In [ ]:
# Clean up a value in director facebook likes
movies1['director_facebook_likes'] = movies1['director_facebook_likes'].str.replace('"', '', regex=False)

In [ ]:
# Rename column titles
movies1.rename(columns={"title_year.1":"title_year_1"}, inplace=True)
movies1.rename(columns={"cast_total_facebook_likes" : "total_cast_facebook_likes"}, inplace=True)
movies1.columns

Index(['movie_title', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes',
       'actor_1_facebook_likes', 'gross', 'num_voted_users',
       'total_cast_facebook_likes', 'facenumber_in_poster',
       'num_user_for_reviews', 'budget', 'title_year',
       'actor_2_facebook_likes', 'imdb_score', 'title_year_1'],
      dtype='object')

In [ ]:
# checking missing values
movies1.isnull().sum()

movie_title                  0
num_critic_for_reviews       0
duration                     3
director_facebook_likes      2
actor_3_facebook_likes       0
actor_1_facebook_likes       0
gross                        0
num_voted_users              1
total_cast_facebook_likes    2
facenumber_in_poster         5
num_user_for_reviews         0
budget                       0
title_year                   0
actor_2_facebook_likes       1
imdb_score                   0
title_year_1                 7
dtype: int64

In [ ]:
movies1

,movie_title,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,total_cast_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,title_year_1
0,Avatar?ÿ,723,178.0,10,855,1000,760505847,886204.0,4834.0,NaN,3054,237000000,2009,936.0,7.9,2009.0
1,Pirates of the Caribbean: At World's End?ÿ,302,NaN,563,1000,40000,309404152,471220.0,48350.0,NaN,1238,300000000,2007,5000.0,7.1,NaN
2,Spectre?ÿ,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
3,The Dark Knight Rises?ÿ,813,NaN,22000,23000,27000,448130642,1144337.0,106759.0,NaN,2701,250000000,2012,23000.0,8.5,NaN
4,John Carter?ÿ,462,132.0,475,530,640,73058679,212204.0,1873.0,1.0,738,263700000,2012,632.0,6.6,NaN
5,Spider-Man 3?ÿ,392,156.0,23,4000,24000,336530303,383056.0,46055.0,NaN,1902,258000000,2007,11000.0,6.2,2007.0
6,Tangled?ÿ,324,NaN,15,284,799,200807262,294810.0,NaN,1.0,387,260000000,2010,553.0,7.8,NaN
7,Avengers: Age of Ultron?ÿ,635,141.0,10,19000,26000,458991599,462669.0,92000.0,4.0,1117,250000000,2015,21000.0,7.5,NaN
8,Avengers: Age of Ultron?ÿ,635,141.0,10,19000,26000,458991599,462669.0,92000.0,4.0,1117,250000000,2015,21000.0,7.5,2015.0
9,Harry Potter and the Half-Blood Prince?ÿ,375,153.0,282,10000,25000,301956980,321795.0,58753.0,3.0,973,250000000,2009,11000.0,7.5,NaN
10,Batman v Superman: Dawn of Justice?ÿ,673,183.0,NaN,2000,15000,330249062,NaN,24450.0,NaN,3018,250000000,2016,NaN,6.9,2016.0
11,Superman Returns?ÿ,434,169.0,NaN,903,18000,200069408,240396.0,NaN,2.0,2367,209000000,2006,10000.0,6.1,NaN
12,Quantum of Solace?ÿ,403,106.0,395,393,451,168368427,330784.0,2023.0,1.0,1243,200000000,2008,412.0,6.7,2008.0
13,Pirates of the Caribbean: Dead Man's Chest?ÿ,313,151.0,563,1000,40000,423032628,522040.0,48486.0,2.0,1832,225000000,2006,5000.0,7.3,2008.0

In [ ]:
# filling in missing values
movies1.fillna({'duration': movies1['duration']. median()},inplace=True)
movies1.fillna({'director_facebook_likes' : movies1['director_facebook_likes'].median()},inplace=True)
movies1.fillna({'facenumber_in_poster' : movies1['facenumber_in_poster'].median()}, inplace=True)
movies1.fillna({'total_cast_facebook_likes' : movies1['total_cast_facebook_likes'].median()}, inplace=True)
movies1.fillna({'num_voted_users': movies1['num_voted_users'].median()}, inplace=True)
movies1.fillna({'actor_2_facebook_likes': movies1['actor_2_facebook_likes'].median()}, inplace=True)
movies1.fillna({'title_year_1' : movies1['title_year']}, inplace=True)

In [ ]:
movies1.isnull().sum()

movie_title                  0
num_critic_for_reviews       0
duration                     0
director_facebook_likes      0
actor_3_facebook_likes       0
actor_1_facebook_likes       0
gross                        0
num_voted_users              0
total_cast_facebook_likes    0
facenumber_in_poster         0
num_user_for_reviews         0
budget                       0
title_year                   0
actor_2_facebook_likes       0
imdb_score                   0
title_year_1                 0
dtype: int64

In [ ]:
# converting data into their right datatypes
movies1 = movies1.astype({'actor_2_facebook_likes':int, 'title_year_1': int, 'total_cast_facebook_likes':int, 'num_voted_users':int, 'director_facebook_likes':int})
movies1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   movie_title                14 non-null     object
 1   num_critic_for_reviews     14 non-null     int64
 2   duration                   14 non-null     float64
 3   director_facebook_likes    14 non-null     int64
 4   actor_3_facebook_likes     14 non-null     int64
 5   actor_1_facebook_likes     14 non-null     int64
 6   gross                      14 non-null     int64
 7   num_voted_users            14 non-null     int64
 8   total_cast_facebook_likes  14 non-null     int64
 9   facenumber_in_poster       14 non-null     float64
 10  num_user_for_reviews       14 non-null     int64
 11  budget                     14 non-null     int64
 12  title_year                 14 non-null     int64
 13  actor_2_facebook_likes     14 non-null     int64
 14  imdb_score                 14 non-null     float64
 15  title_year_1               14 non-null     int64
dtypes: float64(3), int64(12), object(1)
memory usage: 1.9+ KB

In [ ]:
# dealing with the NaN value
movies1['director_facebook_likes'] = pd.to_numeric(movies1['director_facebook_likes'], errors='coerce').fillna(0).astype(int)

In [ ]:
# checking for duplicates
movies1.duplicated().sum()

np.int64(1)

In [ ]:
# drop duplicates
movies1.drop_duplicates(inplace=True)
# check again for duplicates
movies1.duplicated().sum()

np.int64(0)

In [ ]:
# cleaning the movie title column
movies1['movie_title'] = movies1['movie_title'].str[:-2]
movies1.head()

,movie_title,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,total_cast_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,title_year_1
0,Avatar,723,178.0,10,855,1000,760505847,886204,4834,2.0,3054,237000000,2009,936,7.9,2009
1,Pirates of the Caribbean: At World's End,302,151.0,563,1000,40000,309404152,471220,48350,2.0,1238,300000000,2007,5000,7.1,2007
2,Spectre,602,148.0,20,161,11000,200074175,275868,11700,1.0,994,245000000,2015,393,6.8,2015
3,The Dark Knight Rises,813,151.0,22000,23000,27000,448130642,1144337,106759,2.0,2701,250000000,2012,23000,8.5,2012
4,John Carter,462,132.0,475,530,640,73058679,212204,1873,1.0,738,263700000,2012,632,6.6,2012

In [ ]:
movies1

,movie_title,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,total_cast_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,title_year_1
0,Avatar,723,178.0,10,855,1000,760505847,886204,4834,2.0,3054,237000000,2009,936,7.9,2009
1,Pirates of the Caribbean: At World's End,302,151.0,563,1000,40000,309404152,471220,48350,2.0,1238,300000000,2007,5000,7.1,2007
2,Spectre,602,148.0,20,161,11000,200074175,275868,11700,1.0,994,245000000,2015,393,6.8,2015
3,The Dark Knight Rises,813,151.0,22000,23000,27000,448130642,1144337,106759,2.0,2701,250000000,2012,23000,8.5,2012
4,John Carter,462,132.0,475,530,640,73058679,212204,1873,1.0,738,263700000,2012,632,6.6,2012
5,Spider-Man 3,392,156.0,23,4000,24000,336530303,383056,46055,2.0,1902,258000000,2007,11000,6.2,2007
6,Tangled,324,151.0,15,284,799,200807262,294810,47202,1.0,387,260000000,2010,553,7.8,2010
7,Avengers: Age of Ultron,635,141.0,10,19000,26000,458991599,462669,92000,4.0,1117,250000000,2015,21000,7.5,2015
9,Harry Potter and the Half-Blood Prince,375,153.0,282,10000,25000,301956980,321795,58753,3.0,973,250000000,2009,11000,7.5,2009
10,Batman v Superman: Dawn of Justice,673,183.0,0,2000,15000,330249062,383056,24450,2.0,3018,250000000,2016,5000,6.9,2016
11,Superman Returns,434,169.0,0,903,18000,200069408,240396,47202,2.0,2367,209000000,2006,10000,6.1,2006
12,Quantum of Solace,403,106.0,395,393,451,168368427,330784,2023,1.0,1243,200000000,2008,412,6.7,2008
13,Pirates of the Caribbean: Dead Man's Chest,313,151.0,563,1000,40000,423032628,522040,48486,2.0,1832,225000000,2006,5000,7.3,2008

In [ ]:
# outlier handling
movies1['log_budget'] = np.log1p(movies1['budget'])
movies1['log_gross'] = np.log1p(movies1['gross'])
movies1['log_num_voted_users'] = np.log1p(movies1['num_voted_users'])

In [ ]:
movies1.head()

,movie_title,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,total_cast_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,title_year_1,log_budget,log_gross,log_num_voted_users
0,Avatar,723,178.0,10,855,1000,760505847,886204,4834,2.0,3054,237000000,2009,936,7.9,2009,19.283571,20.449494,13.694704
1,Pirates of the Caribbean: At World's End,302,151.0,563,1000,40000,309404152,471220,48350,2.0,1238,300000000,2007,5000,7.1,2007,19.519293,19.550159,13.063082
2,Spectre,602,148.0,20,161,11000,200074175,275868,11700,1.0,994,245000000,2015,393,6.8,2015,19.316769,19.114199,12.527681
3,The Dark Knight Rises,813,151.0,22000,23000,27000,448130642,1144337,106759,2.0,2701,250000000,2012,23000,8.5,2012,19.336971,19.920595,13.950337
4,John Carter,462,132.0,475,530,640,73058679,212204,1873,1.0,738,263700000,2012,632,6.6,2012,19.390323,18.106774,12.265308